name: Veracode Container Image Scan

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: myapp-image
  IMAGE_TAG: latest
  FULL_IMAGE_NAME: myregistry/myapp-image:latest

jobs:
  build-and-container-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t ${{ env.FULL_IMAGE_NAME }} .

       - name: Veracode Container/IaC/Secrets scan
        uses: veracode/container_iac_secrets_scanning@v1.0.4
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          command: "scan"
          type: "image"
          source: ${{ env.FULL_IMAGE_NAME }}
          format: "table"
          fail_build: true

      - name: Push Docker image
        if: success()
        run: docker push ${{ env.FULL_IMAGE_NAME }}
