name: Veracode Container Image Scan

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: myapp-image
  IMAGE_TAG: latest
  FULL_IMAGE_NAME: myregistry/myapp-image:latest

jobs:
  build-and-container-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t ${{ env.FULL_IMAGE_NAME }} .

      - name: Download Veracode Container Scanner CLI
        run: |
          curl -fsSL https://tools.veracode.com/container-security/veracode -o veracode
          chmod +x veracode
          sudo mv veracode /usr/local/bin

      - name: Run Veracode Container Image Scan
        run: |
          veracode image scan ${{ env.FULL_IMAGE_NAME }} \
            --format table \
            --source docker \
            --summary \
            --timeout 300 \
            --fail \
            --customer-key ${{ secrets.VERACODE_API_ID }} \
            --customer-secret ${{ secrets.VERACODE_API_KEY }}

      - name: Push Docker Image
        if: success()
        run: docker push ${{ env.FULL_IMAGE_NAME }}
